# Liste des Cloud Builders : https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL
steps:
- name: "mlops/uv-gcp-cloud-build"
  id: CI
  entrypoint: /bin/bash
  secretEnv: ['SERVICE_ACCOUNT']
  env:
    - PROJECT_ID=$PROJECT_ID
  args:
  - -c
  - |
    echo "$$SERVICE_ACCOUNT" > service_account.json
    if ! gcloud auth activate-service-account --key-file=service_account.json; then
      echo "ERROR: gcloud authenfication failed!"
      exit 1
    fi
    gcloud config set project "$PROJECT_ID"
    chmod a+x install.sh &&
    ./install.sh &&
    source .venv/bin/activate &&
    pytest .

logs_bucket: gs://mlops/logs_build_cloud_build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloud-build/versions/1
    env: SERVICE_ACCOUNT