test_ratio: 0.3
automl_max_evals: 10
gcp_project_id: "enhanced-kiln-451309-q8"
gcs_primary_folder: "housing-price-predict/primary"
mlflow_enabled: True # Do we log metrics and artifacts to MLflow ?
mlflow_experiment_id: 1 # Experimented ID associated to this project